POST http://localhost:3000/v1/transfers
Content-Type: application/json

{
  "from_account": "cjld2cyuq0000t3rmniod1foy",
  "to_account": "cldmt86vb0023356kz6cc10p0",
  "amount": "0.000001"
}

###

GET http://localhost:3000/v1/transfers?account_id=cjld2cyuq0000t3rmniod1foy


###

http://localhost:3000/v1/accounts/cldmt86vb0023356kz6cc10pj